let name ="Ivy Marfo";
console.log(name);
let age =89;
console.log(age);
let sum =10+15;
console.log(sum);
let difference = 20 -5;
console.log(difference);
let divided =50/5;
console.log(divide);
let product =7*6;
let remainder =15% 4;
console.log(remainder);
let student = false;
console.log(student);
let variable = 150;
console.log(typeof(variable));
variable ="hello,where is my food?";
console.log(typeof(variable));